#!/bin/bash

ABS_DIR=`pwd -P`
BASE_DIR="${HOME}/rendu"
PROJECT=""
REPO=""

[ -z "${LOGIN}" ] && LOGIN=`whoami`

error()
{
    echo "$1" >&4
    exit 1
}

alert()
{
    echo "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!" >&4
    echo "$1" >&4
    echo "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!" >&4
}

warning()
{
    echo "$1" >&4
}

verbose()
{
    echo "$1" >&3
}

_init()
{
    is_local_repo "${ABS_DIR}" || error "Not in ~/rendu/your_project"
    build_project_name
    [ -z "${PROJECT}" ] && error "Can't guess project name"
    build_repo_name
    [ -z "${REPO}" ] && error "Can't guess repository name"
    cd "${BASE_DIR}/${PROJECT}" || error "Can't chdir to ${BASE_DIR}/${PROJECT}..."
}

#check if we are in a good directory (/home/login/rendu/*)
is_local_repo()
{
    echo "$1" | grep -q -E "^${BASE_DIR}/+[a-zA-Z0-9_.-]+/*$"
    return $?
}

build_project_name()
{
    PROJECT=`basename "$ABS_DIR"`
}

build_repo_name()
{
    REPO="${PROJECT}"
}
